# Generated by Django 2.2.16 on 2021-05-15 22:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_equipe', models.CharField(max_length=250)),
                ('lose_equipe', models.CharField(max_length=250)),
                ('is_null', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Paris Liste',
                'verbose_name_plural': 'Listes des Paris',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=200)),
                ('sport_key', models.CharField(max_length=100)),
                ('sport_nice', models.CharField(max_length=100)),
                ('team1', models.CharField(max_length=250)),
                ('team2', models.CharField(max_length=250)),
                ('home_team', models.CharField(max_length=250)),
                ('commence_time', models.DateTimeField(max_length=100)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('site_key', models.CharField(max_length=100)),
                ('site_nice', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(max_length=100)),
                ('win', models.CharField(max_length=100)),
                ('null', models.CharField(max_length=100)),
                ('lose', models.CharField(max_length=100)),
                ('is_use', models.BooleanField(default=False)),
                ('is_end', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sports Liste',
                'verbose_name_plural': 'Listes des Sports',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Liste',
                'verbose_name_plural': 'Listes des transactions',
            },
        ),
        migrations.CreateModel(
            name='WalletRequested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(default=0)),
                ('ref_code', models.CharField(max_length=6)),
                ('is_complete', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expiry', models.DateTimeField(default=datetime.datetime(2021, 5, 15, 22, 32, 14, 484915, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recharge Liste',
                'verbose_name_plural': 'Listes des recharges',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille Liste',
                'verbose_name_plural': 'Listes des portefeuilles',
            },
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(default=0)),
                ('is_done', models.BooleanField(default=True)),
                ('envoyer', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retrait Liste',
                'verbose_name_plural': 'Listes des retraits',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('photo', models.ImageField(blank=True, default='photo.jpg', null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Liste',
                'verbose_name_plural': 'Listes des profiles',
            },
        ),
        migrations.CreateModel(
            name='BetActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_position', models.CharField(max_length=250)),
                ('is_end', models.BooleanField(default=False)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bet.Bet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ParisActive Liste',
                'verbose_name_plural': 'Listes des ParisActive',
            },
        ),
        migrations.AddField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bet.Game'),
        ),
        migrations.AddField(
            model_name='bet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
