# Generated by Django 2.2.16 on 2021-05-29 03:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletrequested',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 3, 49, 31, 251024, tzinfo=utc)),
        ),
    ]
