# Generated by Django 2.2.16 on 2021-05-29 03:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_auto_20210528_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='groupe',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='walletrequested',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 3, 57, 35, 923830, tzinfo=utc)),
        ),
    ]
