# Generated by Django 2.2.16 on 2021-05-16 15:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bet', '0002_auto_20210515_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_end',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_use',
        ),
        migrations.AddField(
            model_name='game',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='bet.Profile'),
        ),
        migrations.AlterField(
            model_name='walletrequested',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 15, 37, 38, 613615, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
