# Generated by Django 2.2.16 on 2021-05-28 04:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_auto_20210525_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_baseball',
            new_name='is_other',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_basket',
        ),
        migrations.AlterField(
            model_name='walletrequested',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 5, 11, 7, 836001, tzinfo=utc)),
        ),
    ]
