# Generated by Django 2.2.16 on 2021-05-29 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0003_auto_20210528_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='game',
            name='lose',
        ),
        migrations.RemoveField(
            model_name='game',
            name='null',
        ),
        migrations.RemoveField(
            model_name='game',
            name='site_key',
        ),
        migrations.RemoveField(
            model_name='game',
            name='site_nice',
        ),
        migrations.RemoveField(
            model_name='game',
            name='win',
        ),
        migrations.AlterField(
            model_name='walletrequested',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 13, 54, 57, 25146, tzinfo=utc)),
        ),
    ]
