# Generated by Django 2.2.16 on 2021-05-16 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0003_auto_20210516_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_live',
        ),
        migrations.AddField(
            model_name='game',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='walletrequested',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 15, 50, 1, 225359, tzinfo=utc)),
        ),
    ]
