# Generated by Django 2.2.16 on 2021-05-16 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0004_auto_20210516_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='lose_equipe',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='win_equipe',
        ),
        migrations.AddField(
            model_name='bet',
            name='winning_equipe',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='walletrequested',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 21, 0, 50, 677680, tzinfo=utc)),
        ),
    ]
