# Generated by Django 2.2.16 on 2021-05-16 23:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0005_auto_20210516_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletrequested',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 0, 2, 49, 65582, tzinfo=utc)),
        ),
    ]
