# Generated by Django 2.2.16 on 2021-05-17 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0006_auto_20210516_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletrequested',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 10, 39, 6, 245961, tzinfo=utc)),
        ),
    ]
